### ISSUE TITLE
Application Logo

### ISSUE THREAD

**Issue by rohsaurus** [rohsaurus/Cerberus-Military-Grade-File-Encryption-Application#27]
Help Wanted in designing a logo and icon for the application.

**Comment by rid181198** [comment]
Hello, I would like to help. Let me know.

**Comment by rohsaurus** [comment]
> Hello, I would like to help. Let me know.

Hey Ridhesh, I'd love that! Currently I'm contributing to a different branch, so the current release is outdated. If you'd like, I could build you a binary, so you could explore the color scheme of the app. I'd love to hear your ideas on what you were thinking the icon could look like!

**Comment by rid181198** [comment]
Please share it with me. Could you give me some idea of what kind of icon are you looking for?

**Comment by rohsaurus** [comment]
> Please share it with me. Could you give me some idea of what kind of icon are you looking for?
> 

Do you you need Linux or Windows? 

As for the icon, I'm not 100% sure with what I want. On the login and sign up screens, I have pictures of the Alps in the background, so maybe a something like the logo Nordlocker has? I'm open to ideas.

**Comment by zbrianhuang** [comment]
Can i help otoo?

**Comment by rohsaurus** [comment]
@rid181198 I just recently published the latest version and you may download them here https://github.com/rohsaurus/Cerberus/releases/tag/0.8.0-alpha
